<?php

namespace App\DataFixtures;

use App\Entity\Audio;
use App\Entity\Boat;
use App\Entity\Characteristics;
use App\Entity\Image;
use App\Entity\Schedule;
use App\Entity\Text;
use App\Entity\Visit;
use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Persistence\ObjectManager;
use Symfony\Component\Mime\CharacterStream;

class AppFixtures extends Fixture
{
    public function load(ObjectManager $manager): void
    {
        // France 1
        $france1 = new Boat();
        $france1->setName("France 1");
        $france1->setHistoric("Le France 1 a assuré ses missions pendant 27 années jusqu'à l'entrée en service des satellites météorologiques en 1985. Il devait alors opérer de longues stations sur les lieux de formation et de passage des pires dépressions au large de l'océan Atlantique. Fouetté par des vents atteignant parfois 100 nœuds (180 km/h), balancé par des creux de 20 mètres, ce navire, quel que soit le temps, a rempli sa mission pendant près de 30 ans, et a fait la pluie et le beau temps pour la Météorologie Nationale.");
        $france1->setState("1");
        $france1->setStateText("Ouvert");
        $france1->setLat("46.15085659418591");
        $france1->setLng("-1.1517760553310752");
        $france1->setImage("img/france1-1.jpg");
        $manager->persist($france1);
        $caracteristiquesFrance1 = new Characteristics();
        $caracteristiquesFrance1->setBoat($france1);
        $caracteristiquesFrance1->setStartYear("1958");
        $caracteristiquesFrance1->setMaterial("Acier");
        $caracteristiquesFrance1->setRestore("2004 à 2005");
        $caracteristiquesFrance1->setInitialOwner("Ville de La Rochelle");
        $caracteristiquesFrance1->setInitialHarbor("La Rochelle");
        $caracteristiquesFrance1->setCollectionEntry("1988");
        $caracteristiquesFrance1->setBuyPrice("1,2 MF");
        $caracteristiquesFrance1->setHistoricMonumentRankDate("24/02/2004");
        $manager->persist($caracteristiquesFrance1);
        $audioFrance1 = new Audio();
        $audioFrance1->setBoat($france1);
        $audioFrance1->setTitle("Le France 1 en audio...");
        $audioFrance1->setFile("audio/france1.mp3");
        $manager->persist($audioFrance1);
        $image1France1 = new Image();
        $image1France1->setBoat($france1);
        $image1France1->setDescription("Déplacement du France 1, tiré par un remorqueur");
        $image1France1->setImage("img/france1-2.jpg");
        $manager->persist($image1France1);
        $image2France1 = new Image();
        $image2France1->setBoat($france1);
        $image2France1->setDescription("Barre du France 1");
        $image2France1->setImage("img/france1-3.jpg");
        $manager->persist($image2France1);
        $temoignageFrance1 = new Text();
        $temoignageFrance1->setBoat($france1);
        $temoignageFrance1->setTitle("Un membre de l'équipage");
        $temoignageFrance1->setTestimony("Quand on était en route, il y avait un officier de quart et un matelot de passerelle, mais en pêche j’étais à la passerelle de 6 heures à minuit et encore minuit et 6 heures je me relevais à chaque virage de chalut. L’Angoumois était à la vente le lundi, puis à la marée suivante le mercredi. Entre deux marées, trois jours d’arrêt. L’hiver on se rapprochait 24 heures à l’avance pour arriver à temps. En janvier 1986, on a essuyé un ouragan (force 12), on est resté 80 heures à la cape. Il y avait de quoi avoir peur.");
        $manager->persist($temoignageFrance1);
        $visitLundiFrance1 = new Visit();
        $visitLundiFrance1->setDay("monday");
        $visitLundiFrance1->setBoat($france1);
        $visitLundiFrance1->setMaximumPlaces(50);
        $visitLundiFrance1->setActual(0);
        $visitLundiFrance1->setVisitTime(30);
        $manager->persist($visitLundiFrance1);
        $visitMardiFrance1 = new Visit();
        $visitMardiFrance1->setDay("tuesday");
        $visitMardiFrance1->setBoat($france1);
        $visitMardiFrance1->setMaximumPlaces(50);
        $visitMardiFrance1->setActual(0);
        $visitMardiFrance1->setVisitTime(30);
        $manager->persist($visitMardiFrance1);
        $visitMercrediFrance1 = new Visit();
        $visitMercrediFrance1->setDay("wednesday");
        $visitMercrediFrance1->setBoat($france1);
        $visitMercrediFrance1->setMaximumPlaces(50);
        $visitMercrediFrance1->setActual(0);
        $visitMercrediFrance1->setVisitTime(30);
        $manager->persist($visitMercrediFrance1);
        $visitJeudiFrance1 = new Visit();
        $visitJeudiFrance1->setDay("thursday");
        $visitJeudiFrance1->setBoat($france1);
        $visitJeudiFrance1->setMaximumPlaces(50);
        $visitJeudiFrance1->setActual(0);
        $visitJeudiFrance1->setVisitTime(30);
        $manager->persist($visitJeudiFrance1);
        $visitVendrediFrance1 = new Visit();
        $visitVendrediFrance1->setDay("friday");
        $visitVendrediFrance1->setBoat($france1);
        $visitVendrediFrance1->setMaximumPlaces(50);
        $visitVendrediFrance1->setActual(0);
        $visitVendrediFrance1->setVisitTime(30);
        $manager->persist($visitVendrediFrance1);
        $visitSamediFrance1 = new Visit();
        $visitSamediFrance1->setDay("saturday");
        $visitSamediFrance1->setBoat($france1);
        $visitSamediFrance1->setMaximumPlaces(50);
        $visitSamediFrance1->setActual(0);
        $visitSamediFrance1->setVisitTime(30);
        $manager->persist($visitSamediFrance1);

        // Saint Gilles
        $saintgilles = new Boat();
        $saintgilles->setName("Saint Gilles");
        $saintgilles->setHistoric("Il fut construit en 1958 aux chantiers navals des ACRP à La Rochelle, où il ira par la suite à Saint-Nazaire commencer sa carrière. Il effectuera des remorquages pendant plus de treize ans et retournera à La Rochelle, au port de La Pallice où il sera désarmé en 1989. Après un accident, le président de l'Union des Remorqueurs de l'Océan demande alors au Musée Maritime de La Rochelle d'en assurer la conservation. Le remorqueur sera hissé sur le slipway en septembre 1994 pour une restauration de sa coque et de son pont. L’année d’après, en 1995, Saint-Gilles est classé « monument historique ».");
        $saintgilles->setState("1");
        $saintgilles->setStateText("Ouvert");
        $saintgilles->setLat("46.15115789976202");
        $saintgilles->setLng("-1.1515942240203119");
        $saintgilles->setImage("img/saintgilles1.png");
        $manager->persist($saintgilles);
        $caracteristiquesSaintgilles = new Characteristics();
        $caracteristiquesSaintgilles->setBoat($saintgilles);
        $caracteristiquesSaintgilles->setStartYear("1958");
        $caracteristiquesSaintgilles->setMaterial("Acier");
        $caracteristiquesSaintgilles->setRestore("2013");
        $caracteristiquesSaintgilles->setInitialOwner("Union des remorqueurs de l'océan");
        $caracteristiquesSaintgilles->setInitialHarbor("La Rochelle");
        $caracteristiquesSaintgilles->setCollectionEntry("1989");
        $caracteristiquesSaintgilles->setBuyPrice("150 000 F");
        $caracteristiquesSaintgilles->setHistoricMonumentRankDate("17/05/1995");
        $manager->persist($caracteristiquesSaintgilles);
        $audioSaintgilles = new Audio();
        $audioSaintgilles->setBoat($saintgilles);
        $audioSaintgilles->setTitle("Le Saint Gilles en audio...");
        $audioSaintgilles->setFile("audio/saint-gilles.mp3");
        $manager->persist($audioSaintgilles);
        $image1Saintgilles = new Image();
        $image1Saintgilles->setBoat($saintgilles);
        $image1Saintgilles->setDescription("Le Saint Gilles dans le port de La Rochelle");
        $image1Saintgilles->setImage("img/saintgilles2.jpg");
        $manager->persist($image1Saintgilles);
        $temoignageSaintgilles = new Text();
        $temoignageSaintgilles->setBoat($saintgilles);
        $temoignageSaintgilles->setTitle("");
        $temoignageSaintgilles->setTestimony("");
        $manager->persist($temoignageSaintgilles);
        $visitLundiSaintgilles = new Visit();
        $visitLundiSaintgilles->setDay("monday");
        $visitLundiSaintgilles->setBoat($saintgilles);
        $visitLundiSaintgilles->setMaximumPlaces(50);
        $visitLundiSaintgilles->setActual(0);
        $visitLundiSaintgilles->setVisitTime(30);
        $manager->persist($visitLundiSaintgilles);
        $visitMardiSaintgilles = new Visit();
        $visitMardiSaintgilles->setDay("tuesday");
        $visitMardiSaintgilles->setBoat($saintgilles);
        $visitMardiSaintgilles->setMaximumPlaces(50);
        $visitMardiSaintgilles->setActual(0);
        $visitMardiSaintgilles->setVisitTime(30);
        $manager->persist($visitMardiSaintgilles);
        $visitMercrediSaintgilles = new Visit();
        $visitMercrediSaintgilles->setDay("wednesday");
        $visitMercrediSaintgilles->setBoat($saintgilles);
        $visitMercrediSaintgilles->setMaximumPlaces(50);
        $visitMercrediSaintgilles->setActual(0);
        $visitMercrediSaintgilles->setVisitTime(30);
        $manager->persist($visitMercrediSaintgilles);
        $visitJeudiSaintgilles = new Visit();
        $visitJeudiSaintgilles->setDay("thursday");
        $visitJeudiSaintgilles->setBoat($saintgilles);
        $visitJeudiSaintgilles->setMaximumPlaces(50);
        $visitJeudiSaintgilles->setActual(0);
        $visitJeudiSaintgilles->setVisitTime(30);
        $manager->persist($visitJeudiSaintgilles);
        $visitVendrediSaintgilles = new Visit();
        $visitVendrediSaintgilles->setDay("friday");
        $visitVendrediSaintgilles->setBoat($saintgilles);
        $visitVendrediSaintgilles->setMaximumPlaces(50);
        $visitVendrediSaintgilles->setActual(0);
        $visitVendrediSaintgilles->setVisitTime(30);
        $manager->persist($visitVendrediSaintgilles);
        $visitSamediSaintgilles = new Visit();
        $visitSamediSaintgilles->setDay("saturday");
        $visitSamediSaintgilles->setBoat($saintgilles);
        $visitSamediSaintgilles->setMaximumPlaces(50);
        $visitSamediSaintgilles->setActual(0);
        $visitSamediSaintgilles->setVisitTime(30);
        $manager->persist($visitSamediSaintgilles);

        // Angoumois
        $angoumois = new Boat();
        $angoumois->setName("Angoumois");
        $angoumois->setHistoric("Ce chalutier construit en 1969 par les Ateliers et Chantiers de Dieppe a été commandé par Jean-Claude Menu, Armateur de l’Association Rochelaise de Pêche à Vapeur (ARPV). « L’Angoumois est le deuxième pêche arrière que j’ai fait construire » explique-t-il. « Il a été précédé par le Saintonge. Je voulais des chalutiers de 38 mètres pêche arrière avec rampe et entrepont. Cette disposition n’existait alors que sur les navires de 55 à 65 mètres. Les chantiers de Dieppe ont accepté de les réaliser. Ils se sont révélés d’excellents bateaux. D’ailleurs avec l’Angoumois, je n’ai jamais eu de pépin »");
        $angoumois->setState("1");
        $angoumois->setStateText("Ouvert");
        $angoumois->setLat("46.130479083242327");
        $angoumois->setLng("-1.1515975367774889");
        $angoumois->setImage("img/angoumois1.png");
        $manager->persist($angoumois);
        $caracteristiquesAngoumois = new Characteristics();
        $caracteristiquesAngoumois->setBoat($angoumois);
        $caracteristiquesAngoumois->setStartYear("1969");
        $caracteristiquesAngoumois->setMaterial("Acier");
        $caracteristiquesAngoumois->setRestore("2009 à 2012");
        $caracteristiquesAngoumois->setInitialOwner("ARPV, Association Rochelaise de Pêche à Vapeur");
        $caracteristiquesAngoumois->setInitialHarbor("La Rochelle");
        $caracteristiquesAngoumois->setCollectionEntry("1993");
        $caracteristiquesAngoumois->setBuyPrice("Privé");
        $caracteristiquesAngoumois->setHistoricMonumentRankDate("06/09/1993");
        $manager->persist($caracteristiquesAngoumois);
        $audioAngoumois = new Audio();
        $audioAngoumois->setBoat($angoumois);
        $audioAngoumois->setTitle("Le plus beau des chalutiers...");
        $audioAngoumois->setFile("audio/angoumois.mp3");
        $manager->persist($audioAngoumois);
        $image1Angoumois = new Image();
        $image1Angoumois->setDescription("Photo d'archive de l'Angoumois pendant la pêche");
        $image1Angoumois->setImage("img/angoumois2.jpg");
        $image1Angoumois->setBoat($angoumois);
        $manager->persist($image1Angoumois);
        $image2Angoumois = new Image();
        $image2Angoumois->setBoat($angoumois);
        $image2Angoumois->setDescription("Vue sur l'Angoumois en 2015");
        $image2Angoumois->setImage("img/angoumois3.jpg");
        $manager->persist($image2Angoumois);
        $temoignageAngoumois = new Text();
        $temoignageAngoumois->setBoat($angoumois);
        $temoignageAngoumois->setTitle("Un membre de l'équipage");
        $temoignageAngoumois->setTestimony("Quand on était en route, il y avait un officier de quart et un matelot de passerelle, mais en pêche j’étais à la passerelle de 6 heures à minuit et encore minuit et 6 heures je me relevais à chaque virage de chalut. L’Angoumois était à la vente le lundi, puis à la marée suivante le mercredi. Entre deux marées, trois jours d’arrêt. L’hiver on se rapprochait 24 heures à l’avance pour arriver à temps. En janvier 1986, on a essuyé un ouragan (force 12), on est resté 80 heures à la cape. Il y avait de quoi avoir peur.");
        $manager->persist($temoignageAngoumois);
        $visitLundiAngoumois = new Visit();
        $visitLundiAngoumois->setDay("monday");
        $visitLundiAngoumois->setBoat($angoumois);
        $visitLundiAngoumois->setMaximumPlaces(30);
        $visitLundiAngoumois->setActual(0);
        $visitLundiAngoumois->setVisitTime(30);
        $manager->persist($visitLundiAngoumois);
        $visitMardiAngoumois = new Visit();
        $visitMardiAngoumois->setDay("tuesday");
        $visitMardiAngoumois->setBoat($angoumois);
        $visitMardiAngoumois->setMaximumPlaces(30);
        $visitMardiAngoumois->setActual(0);
        $visitMardiAngoumois->setVisitTime(30);
        $manager->persist($visitMardiAngoumois);
        $visitMercrediAngoumois = new Visit();
        $visitMercrediAngoumois->setDay("wednesday");
        $visitMercrediAngoumois->setBoat($angoumois);
        $visitMercrediAngoumois->setMaximumPlaces(30);
        $visitMercrediAngoumois->setActual(0);
        $visitMercrediAngoumois->setVisitTime(30);
        $manager->persist($visitMercrediAngoumois);
        $visitJeudiAngoumois = new Visit();
        $visitJeudiAngoumois->setDay("thursday");
        $visitJeudiAngoumois->setBoat($angoumois);
        $visitJeudiAngoumois->setMaximumPlaces(30);
        $visitJeudiAngoumois->setActual(0);
        $visitJeudiAngoumois->setVisitTime(30);
        $manager->persist($visitJeudiAngoumois);
        $visitVendrediAngoumois = new Visit();
        $visitVendrediAngoumois->setDay("friday");
        $visitVendrediAngoumois->setBoat($angoumois);
        $visitVendrediAngoumois->setMaximumPlaces(30);
        $visitVendrediAngoumois->setActual(0);
        $visitVendrediAngoumois->setVisitTime(30);
        $manager->persist($visitVendrediAngoumois);
        $visitSamediAngoumois = new Visit();
        $visitSamediAngoumois->setDay("saturday");
        $visitSamediAngoumois->setBoat($angoumois);
        $visitSamediAngoumois->setMaximumPlaces(30);
        $visitSamediAngoumois->setActual(0);
        $visitSamediAngoumois->setVisitTime(30);
        $manager->persist($visitSamediAngoumois);

        // Joshua
        $joshua = new Boat();
        $joshua->setName("Joshua");
        $joshua->setHistoric("Ketch rouge mythique, derrière lequel se dessine en filigrane la silhouette de Bernard Moitessier, grand écrivain de mer et premier homme à avoir eu dans son sillage un tour du monde et demi sur les mers du globe, en solitaire et sans escale. Ce voilier en acier de 12 mètres a été baptisé Joshua en hommage au célèbre navigateur Joshua Slocum.");
        $joshua->setState("1");
        $joshua->setStateText("Ouvert");
        $joshua->setLat("46.151900935823114");
        $joshua->setLng("-1.151397351474135");
        $joshua->setImage("img/joshua3.jpg");
        $manager->persist($joshua);
        $caracteristiquesJoshua = new Characteristics();
        $caracteristiquesJoshua->setBoat($joshua);
        $caracteristiquesJoshua->setStartYear("1962");
        $caracteristiquesJoshua->setMaterial("Acier");
        $caracteristiquesJoshua->setInitialOwner("Bernard Moitessier");
        $caracteristiquesJoshua->setInitialHarbor("Marseille");
        $caracteristiquesJoshua->setCollectionEntry("1990");
        $caracteristiquesJoshua->setBuyPrice("245 000 F (sponsoring)");
        $caracteristiquesJoshua->setHistoricMonumentRankDate("06/09/1993");
        $manager->persist($caracteristiquesJoshua);
        $audioJoshua = new Audio();
        $audioJoshua->setBoat($joshua);
        $audioJoshua->setTitle("Entrée de nuit à SeaPort");
        $audioJoshua->setFile("audio/joshua.mp3");
        $manager->persist($audioJoshua);
        $image2Joshua = new Image();
        $image2Joshua->setBoat($joshua);
        $image2Joshua->setDescription("Photo du Joshua dans le port");
        $image2Joshua->setImage("img/joshua2.jpg");
        $manager->persist($image2Joshua);
        $temoignageJoshua = new Text();
        $temoignageJoshua->setBoat($joshua);
        $temoignageJoshua->setTitle("Joshua ressuscité !");
        $temoignageJoshua->setTestimony("Bernard Moitessier aimait à le dire : Joshua  n’a  pas été sauvé, il a été ressuscité ! Il avait abandonné en 1982 un bateau « mort »… Il a retrouvé à la Rochelle, par la grâce de ceux qui ont œuvré avec Patrick Schnepp, son ketch, Joshua, vivant et très vivant.");
        $manager->persist($temoignageJoshua);
        $visitLundiJoshua = new Visit();
        $visitLundiJoshua->setDay("monday");
        $visitLundiJoshua->setBoat($joshua);
        $visitLundiJoshua->setMaximumPlaces(20);
        $visitLundiJoshua->setActual(0);
        $visitLundiJoshua->setVisitTime(30);
        $manager->persist($visitLundiJoshua);
        $visitMardiJoshua = new Visit();
        $visitMardiJoshua->setDay("tuesday");
        $visitMardiJoshua->setBoat($joshua);
        $visitMardiJoshua->setMaximumPlaces(20);
        $visitMardiJoshua->setActual(0);
        $visitMardiJoshua->setVisitTime(30);
        $manager->persist($visitMardiJoshua);
        $visitMercrediJoshua = new Visit();
        $visitMercrediJoshua->setDay("wednesday");
        $visitMercrediJoshua->setBoat($joshua);
        $visitMercrediJoshua->setMaximumPlaces(20);
        $visitMercrediJoshua->setActual(0);
        $visitMercrediJoshua->setVisitTime(30);
        $manager->persist($visitMercrediJoshua);
        $visitJeudiJoshua = new Visit();
        $visitJeudiJoshua->setDay("thursday");
        $visitJeudiJoshua->setBoat($joshua);
        $visitJeudiJoshua->setMaximumPlaces(20);
        $visitJeudiJoshua->setActual(0);
        $visitJeudiJoshua->setVisitTime(30);
        $manager->persist($visitJeudiJoshua);
        $visitVendrediJoshua = new Visit();
        $visitVendrediJoshua->setDay("friday");
        $visitVendrediJoshua->setBoat($joshua);
        $visitVendrediJoshua->setMaximumPlaces(20);
        $visitVendrediJoshua->setActual(0);
        $visitVendrediJoshua->setVisitTime(30);
        $manager->persist($visitVendrediJoshua);
        $visitSamediJoshua = new Visit();
        $visitSamediJoshua->setDay("saturday");
        $visitSamediJoshua->setBoat($joshua);
        $visitSamediJoshua->setMaximumPlaces(20);
        $visitSamediJoshua->setActual(0);
        $visitSamediJoshua->setVisitTime(30);
        $manager->persist($visitSamediJoshua);

        // Manuel Joel
        $manuelJoel = new Boat();
        $manuelJoel->setName("Manuel Joël");
        $manuelJoel->setHistoric("Construit en 1955 à l'emplacement actuel du musée maritime de La Rochelle, le Manuel Joël a pêché au large dans les eaux du Golfe de Gascogne jusqu'en 1979, puis a pratiqué la navigation côtière au large des Pertuis charentais. En 1992, après 37 années de navigation, son propriétaire, Henri Teillet, en fait don au musée maritime de La Rochelle.");
        $manuelJoel->setState("1");
        $manuelJoel->setStateText("Ouvert");
        $manuelJoel->setLat("46.153292164616474");
        $manuelJoel->setLng("-1.1513310930362313");
        $manuelJoel->setImage("img/manuel-joel1.jpg");
        $manager->persist($manuelJoel);
        $caracteristiquesManuelJoel = new Characteristics();
        $caracteristiquesManuelJoel->setBoat($manuelJoel);
        $caracteristiquesManuelJoel->setStartYear("1954");
        $caracteristiquesManuelJoel->setMaterial("Bois chêne");
        $caracteristiquesManuelJoel->setInitialOwner("Armement Henri Teillet");
        $caracteristiquesManuelJoel->setInitialHarbor("La Rochelle");
        $caracteristiquesManuelJoel->setCollectionEntry("20/12/1991");
        $caracteristiquesManuelJoel->setBuyPrice("Don");
        $caracteristiquesManuelJoel->setHistoricMonumentRankDate("22/09/1994");
        $manager->persist($caracteristiquesManuelJoel);
        $audioManuelJoel = new Audio();
        $audioManuelJoel->setBoat($manuelJoel);
        $audioManuelJoel->setTitle("Françoise Teillet, ravitaillement du Manuel Joël");
        $audioManuelJoel->setFile("audio/manuel-joel.mp3");
        $manager->persist($audioManuelJoel);
        $image1ManuelJoel = new Image();
        $image1ManuelJoel->setDescription("Manuel Joël qui coule le soir du 30 mars 2017 dans le bassin des Chalutiers");
        $image1ManuelJoel->setImage("img/manuel-joel2.jpg");
        $image1ManuelJoel->setBoat($manuelJoel);
        $manager->persist($image1ManuelJoel);
        $image2ManuelJoel = new Image();
        $image2ManuelJoel->setBoat($manuelJoel);
        $image2ManuelJoel->setDescription("Manuel Joël qui coule le soir du 30 mars 2017 dans le bassin des Chalutiers");
        $image2ManuelJoel->setImage("img/manuel-joel3.jpg");
        $manager->persist($image2ManuelJoel);
        $temoignageManuelJoel = new Text();
        $temoignageManuelJoel->setBoat($manuelJoel);
        $temoignageManuelJoel->setTitle("Françoise Teillet, femme du patron du Manuel Joël");
        $temoignageManuelJoel->setTestimony("J’attendais mon mari, mais j’avais énormément de travail. Je m’occupais du bateau, des fournisseurs, des pannes, de la marine, tout. Je m’occupais de toute la paperasse à terre et quand ils étaient en panne au Verdon, à Port Bloc, il fallait aller les chercher en voiture et les ramener le lendemain. J’étais obligée de rester disponible 24 heures sur 24. Il fallait toujours être là. Je participais activement à l’activité de l’armement. mais sans statut social, bénévolement. Pourtant, c’était un travail à plein temps. Maintenant il existe le statut de conjoint collaborateur.");
        $manager->persist($temoignageManuelJoel);
        $visitLundiManuelJoel = new Visit();
        $visitLundiManuelJoel->setDay("monday");
        $visitLundiManuelJoel->setBoat($manuelJoel);
        $visitLundiManuelJoel->setMaximumPlaces(20);
        $visitLundiManuelJoel->setActual(0);
        $visitLundiManuelJoel->setVisitTime(30);
        $manager->persist($visitLundiManuelJoel);
        $visitMardiManuelJoel = new Visit();
        $visitMardiManuelJoel->setDay("tuesday");
        $visitMardiManuelJoel->setBoat($manuelJoel);
        $visitMardiManuelJoel->setMaximumPlaces(20);
        $visitMardiManuelJoel->setActual(0);
        $visitMardiManuelJoel->setVisitTime(30);
        $manager->persist($visitMardiManuelJoel);
        $visitMercrediManuelJoel = new Visit();
        $visitMercrediManuelJoel->setDay("wednesday");
        $visitMercrediManuelJoel->setBoat($manuelJoel);
        $visitMercrediManuelJoel->setMaximumPlaces(20);
        $visitMercrediManuelJoel->setActual(0);
        $visitMercrediManuelJoel->setVisitTime(30);
        $manager->persist($visitMercrediManuelJoel);
        $visitJeudiManuelJoel = new Visit();
        $visitJeudiManuelJoel->setDay("thursday");
        $visitJeudiManuelJoel->setBoat($manuelJoel);
        $visitJeudiManuelJoel->setMaximumPlaces(20);
        $visitJeudiManuelJoel->setActual(0);
        $visitJeudiManuelJoel->setVisitTime(30);
        $manager->persist($visitJeudiManuelJoel);
        $visitVendrediManuelJoel = new Visit();
        $visitVendrediManuelJoel->setDay("friday");
        $visitVendrediManuelJoel->setBoat($manuelJoel);
        $visitVendrediManuelJoel->setMaximumPlaces(20);
        $visitVendrediManuelJoel->setActual(0);
        $visitVendrediManuelJoel->setVisitTime(30);
        $manager->persist($visitVendrediManuelJoel);
        $visitSamediManuelJoel = new Visit();
        $visitSamediManuelJoel->setDay("saturday");
        $visitSamediManuelJoel->setBoat($manuelJoel);
        $visitSamediManuelJoel->setMaximumPlaces(20);
        $visitSamediManuelJoel->setActual(0);
        $visitSamediManuelJoel->setVisitTime(30);
        $manager->persist($visitSamediManuelJoel);

        // Vedette Duperré
        $vedetteDuperre = new Boat();
        $vedetteDuperre->setName("Vedette Duperré");
        $vedetteDuperre->setHistoric("Le 1er Juin 1992, l'escorteur d'escadre Duperré, le plus ancien des bâtiments de combat de la Marine prenait sa retraite après 36 ans de bons et loyaux services, et après avoir parcouru plus de 700 000 miles durant plus de 55 000 heures. La Marine Nationale cède alors la vedette de ce bâtiment d'escadre à La Rochelle. Cette vedette est, en réalité, le canot-major de l'escorteur d'escadre Duperré (1954-1992). Construite à Cherboug-Octeville (Manche) en 1954 par la Direction des constructions et armes navales. C'est une vedette à moteur diesel faisant partie de la dotation réglementaire des bâtiments issus du programme naval de l'après-guerre. La drôme des navires de guerre de cette époque comprenait selon la taille des bâtiments, des chaloupes, des baleinières et des canots pour le commandant, les officiers ou les personnalités de passage lors des mouillages sur rade foraine et pour des services divers lors d'escales en France à ou l'étranger.");
        $vedetteDuperre->setState("1");
        $vedetteDuperre->setStateText("Ouvert");
        $vedetteDuperre->setLat("46.15068405414214");
        $vedetteDuperre->setLng("-1.1519407209703627");
        $vedetteDuperre->setImage("img/duperre1.png");
        $manager->persist($vedetteDuperre);
        $caracteristiquesVedetteDuperre = new Characteristics();
        $caracteristiquesVedetteDuperre->setBoat($vedetteDuperre);
        $caracteristiquesVedetteDuperre->setStartYear("1954");
        $caracteristiquesVedetteDuperre->setMaterial("Bois");
        $caracteristiquesVedetteDuperre->setInitialOwner("Marine Nationale");
        $caracteristiquesVedetteDuperre->setInitialHarbor("Brest");
        $caracteristiquesVedetteDuperre->setCollectionEntry("");
        $caracteristiquesVedetteDuperre->setBuyPrice("Don");
        $caracteristiquesVedetteDuperre->setHistoricMonumentRankDate("");
        $manager->persist($caracteristiquesVedetteDuperre);
        $audioVedetteDuperre = new Audio();
        $audioVedetteDuperre->setBoat($vedetteDuperre);
        $audioVedetteDuperre->setTitle("La vedette Duperré en audio ...");
        $audioVedetteDuperre->setFile("audio/duperre.mp3");
        $manager->persist($audioVedetteDuperre);
        $image1VedetteDuperre = new Image();
        $image1VedetteDuperre->setDescription("Entretien de la vedette Duperré");
        $image1VedetteDuperre->setImage("img/duperre2.png");
        $image1VedetteDuperre->setBoat($vedetteDuperre);
        $manager->persist($image1VedetteDuperre);
        $image2VedetteDuperre = new Image();
        $image2VedetteDuperre->setBoat($vedetteDuperre);
        $image2VedetteDuperre->setDescription("Vedette Duperré à son port");
        $image2VedetteDuperre->setImage("img/duperre3.jpg");
        $manager->persist($image2VedetteDuperre);
        $temoignageVedetteDuperre = new Text();
        $temoignageVedetteDuperre->setBoat($vedetteDuperre);
        $temoignageVedetteDuperre->setTitle("Témoignage du président du Musée Maritime");
        $temoignageVedetteDuperre->setTestimony("Ce joli canot symbolise les liens de La Rochelle avec l'ex-escorteur d'escadre Duperré dont la ville était marraine. Confié au Musée maritime en 1994, il est classé au titre des monuments historiques depuis le 6 décembre 2012.");
        $manager->persist($temoignageVedetteDuperre);
        $visitLundiVedetteDuperre = new Visit();
        $visitLundiVedetteDuperre->setDay("monday");
        $visitLundiVedetteDuperre->setBoat($vedetteDuperre);
        $visitLundiVedetteDuperre->setMaximumPlaces(15);
        $visitLundiVedetteDuperre->setActual(0);
        $visitLundiVedetteDuperre->setVisitTime(30);
        $manager->persist($visitLundiVedetteDuperre);
        $visitMardiVedetteDuperre = new Visit();
        $visitMardiVedetteDuperre->setDay("tuesday");
        $visitMardiVedetteDuperre->setBoat($vedetteDuperre);
        $visitMardiVedetteDuperre->setMaximumPlaces(15);
        $visitMardiVedetteDuperre->setActual(0);
        $visitMardiVedetteDuperre->setVisitTime(30);
        $manager->persist($visitMardiVedetteDuperre);
        $visitMercrediVedetteDuperre = new Visit();
        $visitMercrediVedetteDuperre->setDay("wednesday");
        $visitMercrediVedetteDuperre->setBoat($vedetteDuperre);
        $visitMercrediVedetteDuperre->setMaximumPlaces(15);
        $visitMercrediVedetteDuperre->setActual(0);
        $visitMercrediVedetteDuperre->setVisitTime(30);
        $manager->persist($visitMercrediVedetteDuperre);
        $visitJeudiVedetteDuperre = new Visit();
        $visitJeudiVedetteDuperre->setDay("thursday");
        $visitJeudiVedetteDuperre->setBoat($vedetteDuperre);
        $visitJeudiVedetteDuperre->setMaximumPlaces(15);
        $visitJeudiVedetteDuperre->setActual(0);
        $visitJeudiVedetteDuperre->setVisitTime(30);
        $manager->persist($visitJeudiVedetteDuperre);
        $visitVendrediVedetteDuperre = new Visit();
        $visitVendrediVedetteDuperre->setDay("friday");
        $visitVendrediVedetteDuperre->setBoat($vedetteDuperre);
        $visitVendrediVedetteDuperre->setMaximumPlaces(15);
        $visitVendrediVedetteDuperre->setActual(0);
        $visitVendrediVedetteDuperre->setVisitTime(30);
        $manager->persist($visitVendrediVedetteDuperre);
        $visitSamediVedetteDuperre = new Visit();
        $visitSamediVedetteDuperre->setDay("saturday");
        $visitSamediVedetteDuperre->setBoat($vedetteDuperre);
        $visitSamediVedetteDuperre->setMaximumPlaces(15);
        $visitSamediVedetteDuperre->setActual(0);
        $visitSamediVedetteDuperre->setVisitTime(30);
        $manager->persist($visitSamediVedetteDuperre);

        // TD6
        $TD6 = new Boat();
        $TD6->setName("Drague à vapeur TD6");
        $TD6->setHistoric("Cet énorme bâtiment aidera à débarrasser le port de La Rochelle de nombreuses épaves qui l’encombrent. Capable d’extraire 400 m3 de vase par jour à une profondeur de 5.50 m, cet engin mesure 28,50 m de long. N’ayant pas de moteur de propulsion, La drague est remorquée par les porteurs de vase Saint-Marc et Bout Blanc. La carrière de D6 s’achève fin 1987. Elle est alors vouée à la casse. L’association de sauvegarde « TD6 », présidée par le fondateur du Musée maritime Patrick Schnepp décide de sauver la Drague à vapeur de la ferraille. Elle est classée au titre de Monuments Historiques depuis novembre 1992. ");
        $TD6->setState("1");
        $TD6->setStateText("Ouvert");
        $TD6->setLat("46.15867224799955");
        $TD6->setLng("-1.2095281278277816");
        $TD6->setImage("img/td6-1.png");
        $manager->persist($TD6);
        $caracteristiquesTD6 = new Characteristics();
        $caracteristiquesTD6->setBoat($TD6);
        $caracteristiquesTD6->setStartYear("1906");
        $caracteristiquesTD6->setMaterial("Acier");
        $caracteristiquesTD6->setInitialOwner("Direction Départementale de l'Équipement 17");
        $caracteristiquesTD6->setInitialHarbor("Nantes puis La Rochelle");
        $caracteristiquesTD6->setCollectionEntry("1990");
        $caracteristiquesTD6->setBuyPrice("1 franc symbolique, DDE 17");
        $caracteristiquesTD6->setHistoricMonumentRankDate("06/11/1992");
        $manager->persist($caracteristiquesTD6);
        $audioTD6 = new Audio();
        $audioTD6->setBoat($TD6);
        $audioTD6->setTitle("La drague TD6 en audio ...");
        $audioTD6->setFile("audio/td6.mp3");
        $manager->persist($audioTD6);
        $image1TD6 = new Image();
        $image1TD6->setDescription("La Drague TD6 - Cheminée.");
        $image1TD6->setImage("img/td6-2.jpg");
        $image1TD6->setBoat($TD6);
        $manager->persist($image1TD6);
        $image2TD6 = new Image();
        $image2TD6->setBoat($TD6);
        $image2TD6->setDescription("La Drague TD6 et son porteur le Saint-Marc.");
        $image2TD6->setImage("img/td6-3.jpg");
        $manager->persist($image2TD6);
        $temoignageTD6 = new Text();
        $temoignageTD6->setBoat($TD6);
        $temoignageTD6->setTitle("Cap d'Aunis, la relève de TD6");
        $temoignageTD6->setTestimony("J'étais là pour la mise en route de la Cap d'Aunis. La Cap d'Aunis, à chaque passage, extrait 1000 m3. C'est une drague aspiratrice et ce qu'elle extrait est plus liquide, c'est un mélange eau/vase. Ce n'est pas de la vase concentrée comme ce que l'on enlevait avec les godets et cela équivaut à 800 M3 à chaque passage ! La rotation est beaucoup plus rapide. C'est beaucoup moins dangereux et moins pénible que sur la drague à vapeur où tout était vraiment lourd à manœuvrer. D'ailleurs, ce n'est pas difficile, ils sont 6 à bord…On était 24 sur le train de drague ! Et pour le plan de dragage, nous on le suivait visuellement avec des repères à terre. Tandis que sur la Cap d'Aunis, c'est au GPS !");
        $manager->persist($temoignageTD6);
        $visitLundiTD6 = new Visit();
        $visitLundiTD6->setDay("monday");
        $visitLundiTD6->setBoat($TD6);
        $visitLundiTD6->setMaximumPlaces(15);
        $visitLundiTD6->setActual(0);
        $visitLundiTD6->setVisitTime(30);
        $manager->persist($visitLundiTD6);
        $visitMardiTD6 = new Visit();
        $visitMardiTD6->setDay("tuesday");
        $visitMardiTD6->setBoat($TD6);
        $visitMardiTD6->setMaximumPlaces(15);
        $visitMardiTD6->setActual(0);
        $visitMardiTD6->setVisitTime(30);
        $manager->persist($visitMardiTD6);
        $visitMercrediTD6 = new Visit();
        $visitMercrediTD6->setDay("wednesday");
        $visitMercrediTD6->setBoat($TD6);
        $visitMercrediTD6->setMaximumPlaces(15);
        $visitMercrediTD6->setActual(0);
        $visitMercrediTD6->setVisitTime(30);
        $manager->persist($visitMercrediTD6);
        $visitJeudiTD6 = new Visit();
        $visitJeudiTD6->setDay("thursday");
        $visitJeudiTD6->setBoat($TD6);
        $visitJeudiTD6->setMaximumPlaces(15);
        $visitJeudiTD6->setActual(0);
        $visitJeudiTD6->setVisitTime(30);
        $manager->persist($visitJeudiTD6);
        $visitVendrediTD6 = new Visit();
        $visitVendrediTD6->setDay("friday");
        $visitVendrediTD6->setBoat($TD6);
        $visitVendrediTD6->setMaximumPlaces(15);
        $visitVendrediTD6->setActual(0);
        $visitVendrediTD6->setVisitTime(30);
        $manager->persist($visitVendrediTD6);
        $visitSamediTD6 = new Visit();
        $visitSamediTD6->setDay("saturday");
        $visitSamediTD6->setBoat($TD6);
        $visitSamediTD6->setMaximumPlaces(15);
        $visitSamediTD6->setActual(0);
        $visitSamediTD6->setVisitTime(30);
        $manager->persist($visitSamediTD6);
        
        // Leverger
        $leverger = new Boat();
        $leverger->setName("Capitaine de frégate Leverger");
        $leverger->setHistoric("Les Sociétés de Sauvetage en Mer sont le symbole vivant de la solidarité des gens de la mer, de leur abnégation, de leur courage et de leur dévouement. Cette association a pour vocation de secourir les personnes en mer et sur le littoral. Dès sa création, le musée maritime de La Rochelle a eu à cœur de doter sa flotte patrimoniale d’un canot de la SNSM. Appelés canots tous temps (CTT), ils sont emblématiques de la société de sauvetage car ils sont capables de sortir dans n’importe quelles conditions météorologiques pour effectuer des opérations de sauvetage.");
        $leverger->setState("1");
        $leverger->setStateText("Ouvert");
        $leverger->setLat("46.15440605025696");
        $leverger->setLng("-1.1502953851797646");
        $leverger->setImage("img/leverger1.png");
        $manager->persist($leverger);
        $caracteristiquesLeverger = new Characteristics();
        $caracteristiquesLeverger->setBoat($leverger);
        $caracteristiquesLeverger->setStartYear("1954");
        $caracteristiquesLeverger->setMaterial("Acajou/cuivre");
        $caracteristiquesLeverger->setInitialOwner("SNSM");
        $caracteristiquesLeverger->setInitialHarbor("Arcachon");
        $caracteristiquesLeverger->setCollectionEntry("1992");
        $caracteristiquesLeverger->setBuyPrice("Don");
        $caracteristiquesLeverger->setHistoricMonumentRankDate("");
        $manager->persist($caracteristiquesLeverger);
        $audioLeverger = new Audio();
        $audioLeverger->setBoat($leverger);
        $audioLeverger->setTitle("Capitaine de frégate Leverger en audio ...");
        $audioLeverger->setFile("audio/leverger.mp3");
        $manager->persist($audioLeverger);
        $image1Leverger = new Image();
        $image1Leverger->setDescription("Capitaine de frégate Leverger en pleine mer 1966");
        $image1Leverger->setImage("img/leverger2.jpg");
        $image1Leverger->setBoat($leverger);
        $manager->persist($image1Leverger);
        $image2Leverger = new Image();
        $image2Leverger->setBoat($leverger);
        $image2Leverger->setDescription("Sortie du port 2016");
        $image2Leverger->setImage("img/leverger3.jpg");
        $manager->persist($image2Leverger);
        $temoignageLeverger = new Text();
        $temoignageLeverger->setBoat($leverger);
        $temoignageLeverger->setTitle("Leverger, notre sauveur !");
        $temoignageLeverger->setTestimony("Ce canot a effectué de nombreux sauvetages lorsqu'il était attribué à la station de sauvetage d'Arcachon");
        $manager->persist($temoignageLeverger);
        $visitLundiLeverger = new Visit();
        $visitLundiLeverger->setDay("monday");
        $visitLundiLeverger->setBoat($leverger);
        $visitLundiLeverger->setMaximumPlaces(20);
        $visitLundiLeverger->setActual(0);
        $visitLundiLeverger->setVisitTime(30);
        $manager->persist($visitLundiLeverger);
        $visitMardiLeverger = new Visit();
        $visitMardiLeverger->setDay("tuesday");
        $visitMardiLeverger->setBoat($leverger);
        $visitMardiLeverger->setMaximumPlaces(20);
        $visitMardiLeverger->setActual(0);
        $visitMardiLeverger->setVisitTime(30);
        $manager->persist($visitMardiLeverger);
        $visitMercrediLeverger = new Visit();
        $visitMercrediLeverger->setDay("wednesday");
        $visitMercrediLeverger->setBoat($leverger);
        $visitMercrediLeverger->setMaximumPlaces(20);
        $visitMercrediLeverger->setActual(0);
        $visitMercrediLeverger->setVisitTime(30);
        $manager->persist($visitMercrediLeverger);
        $visitJeudiLeverger = new Visit();
        $visitJeudiLeverger->setDay("thursday");
        $visitJeudiLeverger->setBoat($leverger);
        $visitJeudiLeverger->setMaximumPlaces(20);
        $visitJeudiLeverger->setActual(0);
        $visitJeudiLeverger->setVisitTime(30);
        $manager->persist($visitJeudiLeverger);
        $visitVendrediLeverger = new Visit();
        $visitVendrediLeverger->setDay("friday");
        $visitVendrediLeverger->setBoat($leverger);
        $visitVendrediLeverger->setMaximumPlaces(20);
        $visitVendrediLeverger->setActual(0);
        $visitVendrediLeverger->setVisitTime(30);
        $manager->persist($visitVendrediLeverger);
        $visitSamediLeverger = new Visit();
        $visitSamediLeverger->setDay("saturday");
        $visitSamediLeverger->setBoat($leverger);
        $visitSamediLeverger->setMaximumPlaces(20);
        $visitSamediLeverger->setActual(0);
        $visitSamediLeverger->setVisitTime(30);
        $manager->persist($visitSamediLeverger);

        // Horaires
        $lundi = new Schedule();
        $lundi->setDay("monday");
        $lundi->setOpening("10:00");
        $lundi->setClosing("19:00");
        $manager->persist($lundi);

        $mardi = new Schedule();
        $mardi->setDay("tuesday");
        $mardi->setOpening("10:00");
        $mardi->setClosing("19:00");
        $manager->persist($mardi);

        $mercredi = new Schedule();
        $mercredi->setDay("wednesday");
        $mercredi->setOpening("10:00");
        $mercredi->setClosing("19:00");
        $manager->persist($mercredi);

        $jeudi = new Schedule();
        $jeudi->setDay("thursday");
        $jeudi->setOpening("10:00");
        $jeudi->setClosing("19:00");
        $manager->persist($jeudi);

        $vendredi = new Schedule();
        $vendredi->setDay("friday");
        $vendredi->setOpening("10:00");
        $vendredi->setClosing("19:00");
        $manager->persist($vendredi);

        $samedi = new Schedule();
        $samedi->setDay("saturday");
        $samedi->setOpening("10:00");
        $samedi->setClosing("19:00");
        $manager->persist($samedi);

        $manager->flush();
    }
}
